# Implement Gradient Descent For Neural Network (or Logistic Regression) using FRAMEWORK

### Predicting if a person would buy life insurnace based on his age using logistic regression

In [12]:
# First we will Impliment Gradient Descent using Tensorflow and keras
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [13]:
#importing csv file
df=pd.read_csv("insurance_data.csv")
df.head(1)

age  affordibility  bought_insurance
0   22              1                 0

In [3]:
X= df[["age",'affordibility']]#Independable
y = df['bought_insurance']#Dependable

In [4]:
#training Dataset
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

#### Scaling 'age' column trained and testing dataset for predicting in accurate way


# Only scale the age column 
1. Copying X_train to X_train_scaled as a new variable
2. Then Appending new column name as ['age'] in X_train_scaled and storing the scaled value in this new variable created.

In [5]:
X_train_scaled = X_train.copy()
X_train_scaled ['age']= X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

# Neural Network Image for Understanding
![](nn.png)

Input Neural numbers are 2:
1. Age
2. Affordability
Output will only be the one Neural point which will have two parts:
1. Linear Equation for predicting
2. Sigmoid Function to get output as 0 or 1
Equation wll be :
### y = (w1 x age) + (w2 x affordability) + bias

In [6]:
from tensorflow import keras
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(
    optimizer='adam',
    loss = 'binary_crossentropy',
    metrics=['accuracy']
)

/opt/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [19]:
model.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9091 - loss: 0.4741
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9091 - loss: 0.4740
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9091 - loss: 0.4740
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9091 - loss: 0.4740
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9091 - loss: 0.4740
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9091 - loss: 0.4740
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9091 - loss: 0.4739
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9091 - loss: 0.4739
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9091 - loss: 0.4739
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9091 - loss: 0.4739
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.9091 - loss: 0.4739
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9091 - loss: 0.4738


In [20]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[0.14585795],
       [0.44514644],
       [0.70615214],
       [0.359709  ],
       [0.7856198 ],
       [0.10503094]], dtype=float32)

In [23]:
coef, intercept = model.get_weights()
coef,intercept

(array([[4.688374 ],
        [1.6127906]], dtype=float32),
 array([-3.0333254], dtype=float32))

# Implimenting Neural Network from Scratch in python without using Frameworks
1. Output =={(y = (w1 x age) + (w2 x affordability) + bias) || Sigmoid}
2. input == w1 and w2
3. Loss function = binary cross entropy
4. Predict
5. Fit

In [30]:
# 1.Making Sigmoid function
def sigmoid(X):
    return 1/(1+np.exp(-X))
# Sigmoid = 1/1+(expo x)

In [31]:
# 2. Implimenting binary_crossentropy loss function
def binary_crossentropy(y_true,y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [32]:
# 3. predicting function
def predict(age,affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept # output neuron contains weighted_sum || and passing it to sigmoid
    return sigmoid(weighted_sum)
predict(.47,1)

array([0.6863265], dtype=float32)

In [46]:
#4 Implimenting Custom Model
class myNN:
    def __init__(self):
        self.w1 = 1 
        self.w2 = 1
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'],X['affordibility'],y, epochs, loss_thresold)
        print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
        return sigmoid(weighted_sum)

    def gradient_descent(self, age,affordability, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid(weighted_sum)
            loss = binary_crossentropy(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            
            if loss<=loss_thresold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1, w2, bias

In [56]:
customModel = myNN()
customModel.fit(X_train_scaled,y_train,epochs=8000,loss_thresold=0.4631)

Epoch:0, w1:0.969658454959475, w2:0.9347182610558475, bias:-0.12260602948574655, loss:0.7336775537214856
Epoch:50, w1:1.394779624056331, w2:1.1480008472786323, bias:-1.3099799603288151, loss:0.5703872093625706
Epoch:100, w1:2.0062305067431097, w2:1.4258284724775516, bias:-1.7961473770205647, loss:0.542492464336327
Epoch:150, w1:2.589495750016656, w2:1.569838961106348, bias:-2.158866117705222, loss:0.5226545581109588
Epoch:200, w1:3.134872601135377, w2:1.6499830938423623, bias:-2.4513812592697595, loss:0.5070062930359559
Epoch:250, w1:3.6401315612505196, w2:1.6981341812849664, bias:-2.6996154346856414, loss:0.4941895592891688
Epoch:300, w1:4.106265545232514, w2:1.7299079137764637, bias:-2.917407389292283, loss:0.4835245561584767
Epoch:350, w1:4.535654816305175, w2:1.7532690574870955, bias:-3.11269129372367, loss:0.474573663222572
Epoch:400, w1:4.9311968462529725, w2:1.7723485183375853, bias:-3.2903085029140207, loss:0.4670158373037383
Epoch:430, w1:5.153521153288418, w2:1.78268184631013

In [57]:
coef,intercept

(array([[4.688374 ],
        [1.6127906]], dtype=float32),
 array([-3.0333254], dtype=float32))

In [58]:
X_test_scaled

age  affordibility
12  0.27              0
7   0.60              0
14  0.49              1
10  0.18              1
17  0.58              1
18  0.19              0

In [59]:
customModel.predict(X_test_scaled)

12    0.119382
7     0.426135
14    0.714666
10    0.336388
17    0.799308
18    0.082369
dtype: float64

In [60]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[0.14585795],
       [0.44514644],
       [0.70615214],
       [0.359709  ],
       [0.7856198 ],
       [0.10503094]], dtype=float32)